#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDemo
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AIS20170527144859")]
	public partial class LinqToSqlDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Insertt_Department(t_Department instance);
    partial void Updatet_Department(t_Department instance);
    partial void Deletet_Department(t_Department instance);
    #endregion
		
		public LinqToSqlDataContext() : 
				base(global::MyDemo.Properties.Settings.Default.AIS20170527144859ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LinqToSqlDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqToSqlDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqToSqlDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqToSqlDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<t_Department> t_Department
		{
			get
			{
				return this.GetTable<t_Department>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_Department")]
	public partial class t_Department : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _FItemID;
		
		private string _FBrNO;
		
		private System.Nullable<int> _FManager;
		
		private string _FPhone;
		
		private string _FFax;
		
		private string _FNote;
		
		private string _FNumber;
		
		private string _FName;
		
		private System.Nullable<int> _FParentID;
		
		private int _FDProperty;
		
		private System.Nullable<int> _FDStock;
		
		private short _FDeleted;
		
		private string _FShortNumber;
		
		private int _FAcctID;
		
		private int _FCostAccountType;
		
		private System.Data.Linq.Binary _FModifyTime;
		
		private int _FCalID;
		
		private System.Nullable<int> _FPlanArea;
		
		private int _FOtherARAcctID;
		
		private int _FOtherAPAcctID;
		
		private int _FPreARAcctID;
		
		private int _FPreAPAcctID;
		
		private bool _FIsCreditMgr;
		
		private bool _FIsVDept;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFItemIDChanging(int value);
    partial void OnFItemIDChanged();
    partial void OnFBrNOChanging(string value);
    partial void OnFBrNOChanged();
    partial void OnFManagerChanging(System.Nullable<int> value);
    partial void OnFManagerChanged();
    partial void OnFPhoneChanging(string value);
    partial void OnFPhoneChanged();
    partial void OnFFaxChanging(string value);
    partial void OnFFaxChanged();
    partial void OnFNoteChanging(string value);
    partial void OnFNoteChanged();
    partial void OnFNumberChanging(string value);
    partial void OnFNumberChanged();
    partial void OnFNameChanging(string value);
    partial void OnFNameChanged();
    partial void OnFParentIDChanging(System.Nullable<int> value);
    partial void OnFParentIDChanged();
    partial void OnFDPropertyChanging(int value);
    partial void OnFDPropertyChanged();
    partial void OnFDStockChanging(System.Nullable<int> value);
    partial void OnFDStockChanged();
    partial void OnFDeletedChanging(short value);
    partial void OnFDeletedChanged();
    partial void OnFShortNumberChanging(string value);
    partial void OnFShortNumberChanged();
    partial void OnFAcctIDChanging(int value);
    partial void OnFAcctIDChanged();
    partial void OnFCostAccountTypeChanging(int value);
    partial void OnFCostAccountTypeChanged();
    partial void OnFModifyTimeChanging(System.Data.Linq.Binary value);
    partial void OnFModifyTimeChanged();
    partial void OnFCalIDChanging(int value);
    partial void OnFCalIDChanged();
    partial void OnFPlanAreaChanging(System.Nullable<int> value);
    partial void OnFPlanAreaChanged();
    partial void OnFOtherARAcctIDChanging(int value);
    partial void OnFOtherARAcctIDChanged();
    partial void OnFOtherAPAcctIDChanging(int value);
    partial void OnFOtherAPAcctIDChanged();
    partial void OnFPreARAcctIDChanging(int value);
    partial void OnFPreARAcctIDChanged();
    partial void OnFPreAPAcctIDChanging(int value);
    partial void OnFPreAPAcctIDChanged();
    partial void OnFIsCreditMgrChanging(bool value);
    partial void OnFIsCreditMgrChanged();
    partial void OnFIsVDeptChanging(bool value);
    partial void OnFIsVDeptChanged();
    #endregion
		
		public t_Department()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FItemID", DbType="Int NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public int FItemID
		{
			get
			{
				return this._FItemID;
			}
			set
			{
				if ((this._FItemID != value))
				{
					this.OnFItemIDChanging(value);
					this.SendPropertyChanging();
					this._FItemID = value;
					this.SendPropertyChanged("FItemID");
					this.OnFItemIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FBrNO", DbType="VarChar(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string FBrNO
		{
			get
			{
				return this._FBrNO;
			}
			set
			{
				if ((this._FBrNO != value))
				{
					this.OnFBrNOChanging(value);
					this.SendPropertyChanging();
					this._FBrNO = value;
					this.SendPropertyChanged("FBrNO");
					this.OnFBrNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FManager", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> FManager
		{
			get
			{
				return this._FManager;
			}
			set
			{
				if ((this._FManager != value))
				{
					this.OnFManagerChanging(value);
					this.SendPropertyChanging();
					this._FManager = value;
					this.SendPropertyChanged("FManager");
					this.OnFManagerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FPhone", DbType="VarChar(30)", UpdateCheck=UpdateCheck.Never)]
		public string FPhone
		{
			get
			{
				return this._FPhone;
			}
			set
			{
				if ((this._FPhone != value))
				{
					this.OnFPhoneChanging(value);
					this.SendPropertyChanging();
					this._FPhone = value;
					this.SendPropertyChanged("FPhone");
					this.OnFPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FFax", DbType="VarChar(30)", UpdateCheck=UpdateCheck.Never)]
		public string FFax
		{
			get
			{
				return this._FFax;
			}
			set
			{
				if ((this._FFax != value))
				{
					this.OnFFaxChanging(value);
					this.SendPropertyChanging();
					this._FFax = value;
					this.SendPropertyChanged("FFax");
					this.OnFFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FNote", DbType="VarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string FNote
		{
			get
			{
				return this._FNote;
			}
			set
			{
				if ((this._FNote != value))
				{
					this.OnFNoteChanging(value);
					this.SendPropertyChanging();
					this._FNote = value;
					this.SendPropertyChanged("FNote");
					this.OnFNoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FNumber", DbType="VarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string FNumber
		{
			get
			{
				return this._FNumber;
			}
			set
			{
				if ((this._FNumber != value))
				{
					this.OnFNumberChanging(value);
					this.SendPropertyChanging();
					this._FNumber = value;
					this.SendPropertyChanged("FNumber");
					this.OnFNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FName", DbType="VarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string FName
		{
			get
			{
				return this._FName;
			}
			set
			{
				if ((this._FName != value))
				{
					this.OnFNameChanging(value);
					this.SendPropertyChanging();
					this._FName = value;
					this.SendPropertyChanged("FName");
					this.OnFNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FParentID", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> FParentID
		{
			get
			{
				return this._FParentID;
			}
			set
			{
				if ((this._FParentID != value))
				{
					this.OnFParentIDChanging(value);
					this.SendPropertyChanging();
					this._FParentID = value;
					this.SendPropertyChanged("FParentID");
					this.OnFParentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FDProperty", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int FDProperty
		{
			get
			{
				return this._FDProperty;
			}
			set
			{
				if ((this._FDProperty != value))
				{
					this.OnFDPropertyChanging(value);
					this.SendPropertyChanging();
					this._FDProperty = value;
					this.SendPropertyChanged("FDProperty");
					this.OnFDPropertyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FDStock", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> FDStock
		{
			get
			{
				return this._FDStock;
			}
			set
			{
				if ((this._FDStock != value))
				{
					this.OnFDStockChanging(value);
					this.SendPropertyChanging();
					this._FDStock = value;
					this.SendPropertyChanged("FDStock");
					this.OnFDStockChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FDeleted", DbType="SmallInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public short FDeleted
		{
			get
			{
				return this._FDeleted;
			}
			set
			{
				if ((this._FDeleted != value))
				{
					this.OnFDeletedChanging(value);
					this.SendPropertyChanging();
					this._FDeleted = value;
					this.SendPropertyChanged("FDeleted");
					this.OnFDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FShortNumber", DbType="VarChar(80)", UpdateCheck=UpdateCheck.Never)]
		public string FShortNumber
		{
			get
			{
				return this._FShortNumber;
			}
			set
			{
				if ((this._FShortNumber != value))
				{
					this.OnFShortNumberChanging(value);
					this.SendPropertyChanging();
					this._FShortNumber = value;
					this.SendPropertyChanged("FShortNumber");
					this.OnFShortNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAcctID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int FAcctID
		{
			get
			{
				return this._FAcctID;
			}
			set
			{
				if ((this._FAcctID != value))
				{
					this.OnFAcctIDChanging(value);
					this.SendPropertyChanging();
					this._FAcctID = value;
					this.SendPropertyChanged("FAcctID");
					this.OnFAcctIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FCostAccountType", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int FCostAccountType
		{
			get
			{
				return this._FCostAccountType;
			}
			set
			{
				if ((this._FCostAccountType != value))
				{
					this.OnFCostAccountTypeChanging(value);
					this.SendPropertyChanging();
					this._FCostAccountType = value;
					this.SendPropertyChanged("FCostAccountType");
					this.OnFCostAccountTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FModifyTime", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary FModifyTime
		{
			get
			{
				return this._FModifyTime;
			}
			set
			{
				if ((this._FModifyTime != value))
				{
					this.OnFModifyTimeChanging(value);
					this.SendPropertyChanging();
					this._FModifyTime = value;
					this.SendPropertyChanged("FModifyTime");
					this.OnFModifyTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FCalID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int FCalID
		{
			get
			{
				return this._FCalID;
			}
			set
			{
				if ((this._FCalID != value))
				{
					this.OnFCalIDChanging(value);
					this.SendPropertyChanging();
					this._FCalID = value;
					this.SendPropertyChanged("FCalID");
					this.OnFCalIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FPlanArea", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> FPlanArea
		{
			get
			{
				return this._FPlanArea;
			}
			set
			{
				if ((this._FPlanArea != value))
				{
					this.OnFPlanAreaChanging(value);
					this.SendPropertyChanging();
					this._FPlanArea = value;
					this.SendPropertyChanged("FPlanArea");
					this.OnFPlanAreaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOtherARAcctID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int FOtherARAcctID
		{
			get
			{
				return this._FOtherARAcctID;
			}
			set
			{
				if ((this._FOtherARAcctID != value))
				{
					this.OnFOtherARAcctIDChanging(value);
					this.SendPropertyChanging();
					this._FOtherARAcctID = value;
					this.SendPropertyChanged("FOtherARAcctID");
					this.OnFOtherARAcctIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOtherAPAcctID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int FOtherAPAcctID
		{
			get
			{
				return this._FOtherAPAcctID;
			}
			set
			{
				if ((this._FOtherAPAcctID != value))
				{
					this.OnFOtherAPAcctIDChanging(value);
					this.SendPropertyChanging();
					this._FOtherAPAcctID = value;
					this.SendPropertyChanged("FOtherAPAcctID");
					this.OnFOtherAPAcctIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FPreARAcctID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int FPreARAcctID
		{
			get
			{
				return this._FPreARAcctID;
			}
			set
			{
				if ((this._FPreARAcctID != value))
				{
					this.OnFPreARAcctIDChanging(value);
					this.SendPropertyChanging();
					this._FPreARAcctID = value;
					this.SendPropertyChanged("FPreARAcctID");
					this.OnFPreARAcctIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FPreAPAcctID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int FPreAPAcctID
		{
			get
			{
				return this._FPreAPAcctID;
			}
			set
			{
				if ((this._FPreAPAcctID != value))
				{
					this.OnFPreAPAcctIDChanging(value);
					this.SendPropertyChanging();
					this._FPreAPAcctID = value;
					this.SendPropertyChanged("FPreAPAcctID");
					this.OnFPreAPAcctIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIsCreditMgr", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool FIsCreditMgr
		{
			get
			{
				return this._FIsCreditMgr;
			}
			set
			{
				if ((this._FIsCreditMgr != value))
				{
					this.OnFIsCreditMgrChanging(value);
					this.SendPropertyChanging();
					this._FIsCreditMgr = value;
					this.SendPropertyChanged("FIsCreditMgr");
					this.OnFIsCreditMgrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIsVDept", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool FIsVDept
		{
			get
			{
				return this._FIsVDept;
			}
			set
			{
				if ((this._FIsVDept != value))
				{
					this.OnFIsVDeptChanging(value);
					this.SendPropertyChanging();
					this._FIsVDept = value;
					this.SendPropertyChanged("FIsVDept");
					this.OnFIsVDeptChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
