#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDemo
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Mydatabase")]
	public partial class MydatabaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertT_LoginInfo(T_LoginInfo instance);
    partial void UpdateT_LoginInfo(T_LoginInfo instance);
    partial void DeleteT_LoginInfo(T_LoginInfo instance);
    #endregion
		
		public MydatabaseDataContext() : 
				base(global::MyDemo.Properties.Settings.Default.MydatabaseConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MydatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MydatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MydatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MydatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<T_LoginInfo> T_LoginInfo
		{
			get
			{
				return this.GetTable<T_LoginInfo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_LoginInfo")]
	public partial class T_LoginInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _fnumber;
		
		private string _FNAME;
		
		private System.Nullable<char> _FSEX;
		
		private string _FTEL;
		
		private string _FADRESS;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnfnumberChanging(long value);
    partial void OnfnumberChanged();
    partial void OnFNAMEChanging(string value);
    partial void OnFNAMEChanged();
    partial void OnFSEXChanging(System.Nullable<char> value);
    partial void OnFSEXChanged();
    partial void OnFTELChanging(string value);
    partial void OnFTELChanged();
    partial void OnFADRESSChanging(string value);
    partial void OnFADRESSChanged();
    #endregion
		
		public T_LoginInfo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fnumber", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long fnumber
		{
			get
			{
				return this._fnumber;
			}
			set
			{
				if ((this._fnumber != value))
				{
					this.OnfnumberChanging(value);
					this.SendPropertyChanging();
					this._fnumber = value;
					this.SendPropertyChanged("fnumber");
					this.OnfnumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FNAME", DbType="VarChar(255)")]
		public string FNAME
		{
			get
			{
				return this._FNAME;
			}
			set
			{
				if ((this._FNAME != value))
				{
					this.OnFNAMEChanging(value);
					this.SendPropertyChanging();
					this._FNAME = value;
					this.SendPropertyChanged("FNAME");
					this.OnFNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FSEX", DbType="Char(1)")]
		public System.Nullable<char> FSEX
		{
			get
			{
				return this._FSEX;
			}
			set
			{
				if ((this._FSEX != value))
				{
					this.OnFSEXChanging(value);
					this.SendPropertyChanging();
					this._FSEX = value;
					this.SendPropertyChanged("FSEX");
					this.OnFSEXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FTEL", DbType="VarChar(255)")]
		public string FTEL
		{
			get
			{
				return this._FTEL;
			}
			set
			{
				if ((this._FTEL != value))
				{
					this.OnFTELChanging(value);
					this.SendPropertyChanging();
					this._FTEL = value;
					this.SendPropertyChanged("FTEL");
					this.OnFTELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FADRESS", DbType="VarChar(255)")]
		public string FADRESS
		{
			get
			{
				return this._FADRESS;
			}
			set
			{
				if ((this._FADRESS != value))
				{
					this.OnFADRESSChanging(value);
					this.SendPropertyChanging();
					this._FADRESS = value;
					this.SendPropertyChanged("FADRESS");
					this.OnFADRESSChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
